### PR TITLE
rhcos-toolbox: Pass env to sudo when required

### PR DESCRIPTION
**Pull request by ashcrow**
Implements https://bugzilla.redhat.com/show_bug.cgi?id=1792423#c0 which will allow `HTTP_PROXY` and `HTTPS_PROXY` to pass through to `podman`.

### CODE REVIEW

**Comment by miabbott** [comment]
@zonggen was looking at this recently

**Comment by zonggen** [comment]
LGTM, ran locally and works without issue.
Though I was having trouble reproduce the error, what I did was:
 - `cosa run` and [set up proxy with squid for rhcos](https://gist.github.com/zonggen/077278adb6d601e8850f5d874309af5c)
 - then `git clone` the toolbox repo inside rhcos and ran `rhcos-toolbox`

It didn't produce IO timeout after I entered the correct credentials.

**Comment by ashcrow** [comment]
> @zonggen was looking at this recently

I'm happy to pass this off to @zonggen :-)

**Comment by zonggen** [comment]
I think this can be merged

**Pull request merged**
