### PR TITLE
rhcos-toolbox: Use default authfile on pull

### PR DESCRIPTION
**Pull request by ashcrow**
See: https://bugzilla.redhat.com/show_bug.cgi?id=1728062

### CODE REVIEW

**Comment by cgwalters** [comment]
OK, verified too that podman is happy to ignore `ENOENT` on the authfile, so this won't break the "single node debug" case.

**Comment by yuqi-zhang** [comment]
Sorry for the delay in review, I think it would have been better to have it as a variable that you can overwrite from `.toolboxrc`.

**Comment by yuqi-zhang** [comment]
Probably fine as a followup PR though, this works as it stands.

**Comment by cgwalters** [comment]
Configurable is fine, although if you're going to configure it, why wouldn't you just configure `~/.docker/config.json` ?

This actually raises a point that I think we may want to only use the kubeconfig one if it exists, like we did a while ago here https://github.com/openshift/pivot/pull/41

**Pull request merged**
