### PR TITLE
Use RHEL 9 based support-tools image & cleanups

### PR DESCRIPTION
**Pull request by travier**
Remove outdated specfile and NOTICE

---

Update README

---

Use RHEL 9 based support-tools image

See: https://issues.redhat.com/browse/COS-2144
Fixes: https://github.com/coreos/toolbox/issues/84

### CODE REVIEW

**Comment by travier** [comment]
See: https://issues.redhat.com/browse/COS-2144
Fixes: https://github.com/coreos/toolbox/issues/84

**Comment by travier** [comment]
@mike-nguyen This one here needs a regular GitHub Approval :)

**Review by ravanelli — APPROVED** [review]
/lgtm
Not too familiar with toolbox but LGTM

**Pull request merged**
